---
title: hey!
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: judithprays@gmail.com
description: 'testing site leaf and jekyll

'
baseurl: ''
url: testtesttest.com
twitter_username: judithprays
github_username: judithprays
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
